# -*- coding: utf-8 -*-
"""BR-Scan Anomaly Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xIUXLF-oOQosdw_SbusZS7bBlF4WOHT
"""

import torch
import torch.nn as nn
from torchvision import models, transforms
from torch.nn import functional as F
from PIL import Image
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
from google.colab import drive
from tqdm.notebook import tqdm

# --- SECTION 1: STORAGE & MOUNTING ---
print("INITIALIZING D3S DIAGNOSTIC PIPELINE...")
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')
    print("SUCCESS: Google Drive MOUNTED.")
else:
    print("INFO: Google Drive already connected.")

# PATHS - Ensure these match your Drive exactly!
MODEL_PATH = '/content/drive/MyDrive/d3s_resnet50_busi.pth'
ANNOTATED_DATA = '/content/drive/MyDrive/Annotated_Data'

# --- SECTION 2: DYNAMIC PREPROCESSING & NIPPLE MASKING ---

def apply_dynamic_nipple_mask(image_cv):
    """
    Detects the nipple using Hough Circle Transform and masks it
    to prevent anatomical density from causing False Positives.
    """
    gray = cv2.cvtColor(image_cv, cv2.COLOR_RGB2GRAY)
    blurred = cv2.medianBlur(gray, 5)

    # Hough Circles: Adjusted to find the circular density of the nipple
    circles = cv2.HoughCircles(blurred, cv2.HOUGH_GRADIENT, dp=1.2, minDist=100,
                               param1=50, param2=30, minRadius=20, maxRadius=65)

    masked_img = image_cv.copy()
    if circles is not None:
        circles = np.round(circles[0, :]).astype("int")
        for (x, y, r) in circles:
            # Masking the nipple area with absolute black
            cv2.circle(masked_img, (x, y), r + 15, (0, 0, 0), -1)
    return masked_img

def load_diagnostic_model(checkpoint_path, num_classes=3):
    print(f"🔄 STEP 2: VERIFYING RESNET-50 MODEL FILE...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = models.resnet50(weights=None)
    model.fc = nn.Linear(model.fc.in_features, num_classes)

    if os.path.exists(checkpoint_path):
        model.load_state_dict(torch.load(checkpoint_path, map_location=device))
        model.to(device).eval()
        print(f"✅ SUCCESS: Model loaded on {str(device).upper()}.")
        return model, device
    else:
        print(f"❌ ERROR: Model file NOT FOUND at: {checkpoint_path}")
        return None, None

def advanced_shadow_preprocessor(image_path, device):
    """
    Isolates red spectrum, applies dynamic masking, and sharpens density shadows.
    """
    img = cv2.imread(image_path)
    if img is None: return None, None
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 1. Dynamic Nipple Suppression
    img = apply_dynamic_nipple_mask(img)

    # 2. Spectral Enhancement
    red_channel = img[:,:,0]
    # clipLimit=10.0 to amplify subtle malignant shadows
    clahe = cv2.createCLAHE(clipLimit=10.0, tileGridSize=(8,8))
    enhanced_red = clahe.apply(red_channel)

    final_img = np.stack([enhanced_red]*3, axis=-1)

    transform = transforms.Compose([
        transforms.ToPILImage(),
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    return transform(final_img).unsqueeze(0).to(device), img

# --- SECTION 3: BATCH ANALYSIS & VISUALIZATION ---

def run_diagnostic_demo(folder_path, model, device):
    class_labels = ['benign', 'malignant', 'normal']
    stats = {label: 0 for label in class_labels}

    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.png'))]
    print(f"✅ Dataset LOADED: Found {len(files)} scans. Starting Batch Analysis...")

    for filename in tqdm(files, desc="Analyzing Scans"):
        path = os.path.join(folder_path, filename)
        input_tensor, raw_img = advanced_shadow_preprocessor(path, device)
        if input_tensor is None: continue

        # Grad-CAM Heatmap Hook
        features = []
        def hook_fn(module, input, output): features.append(output)
        handle = model.layer4[-1].register_forward_hook(hook_fn)
        output = model(input_tensor)
        handle.remove()

        probs = F.softmax(output, dim=1)
        conf, idx = torch.max(probs, 1)
        stats[class_labels[idx]] += 1

        # Heatmap Generation
        f_map = features[0].detach().cpu().numpy()[0]
        heatmap = np.mean(f_map, axis=0)
        heatmap = np.maximum(heatmap, 0)
        heatmap /= (np.max(heatmap) + 1e-7)
        heatmap = cv2.resize(heatmap, (raw_img.shape[1], raw_img.shape[0]))
        heatmap = np.uint8(255 * heatmap)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
        overlay = cv2.addWeighted(raw_img, 0.6, heatmap, 0.4, 0)

        # Plotting
        plt.figure(figsize=(10, 4))
        plt.subplot(1, 2, 1); plt.imshow(raw_img); plt.title(f"Original: {filename}"); plt.axis('off')
        plt.subplot(1, 2, 2); plt.imshow(overlay); plt.title(f"{class_labels[idx].upper()} ({conf.item()*100:.1f}%)"); plt.axis('off')
        plt.show()

    # Final Report Card
    total = sum(stats.values())
    print("\n" + "="*45)
    print("         D3S BATCH DIAGNOSTIC SUMMARY         ")
    print("="*45)
    for label, count in stats.items():
        pct = (count/total)*100 if total > 0 else 0
        print(f"{label.upper():<12}: {count:>3} images ({pct:>5.1f}%)")
    print("="*45)

# --- FINAL EXECUTION ---
ai_engine, active_device = load_diagnostic_model(MODEL_PATH)
if ai_engine:
    run_diagnostic_demo(ANNOTATED_DATA, ai_engine, active_device)

"""# **different Approach**"""

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
from google.colab import drive
from tqdm.notebook import tqdm

# --- 1. SETUP ---
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# UPDATE THESE PATHS
HEALTHY_TEMPLATE_PATH = '/content/drive/MyDrive/Healthy_images_Data/healthy image1.png' # Your 1 healthy image
UNHEALTHY_FOLDER = '/content/drive/MyDrive/Annotated_Data' # Your 67 images

def run_anomaly_detection():
    # Load the Healthy Template
    template = cv2.imread(HEALTHY_TEMPLATE_PATH)
    if template is None:
        print("❌ Could not load healthy template. Check the path!")
        return

    template = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)
    template = cv2.resize(template, (500, 500))
    # Apply Blur to smooth out hardware noise
    template = cv2.GaussianBlur(template, (21, 21), 0)

    files = [f for f in os.listdir(UNHEALTHY_FOLDER) if f.lower().endswith(('.jpg', '.png'))]
    print(f"🔬 Comparing {len(files)} scans against the Healthy Template...")

    malignant_count = 0
    for filename in tqdm(files):
        path = os.path.join(UNHEALTHY_FOLDER, filename)
        img = cv2.imread(path)
        if img is None: continue

        # Preprocess current scan
        orig = img.copy()
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (500, 500))
        gray = cv2.GaussianBlur(gray, (21, 21), 0)

        # DIFF LOGIC: Subtract the healthy template from the current scan
        # This reveals ONLY the shadows that shouldn't be there
        score, diff = cv2.threshold(cv2.absdiff(template, gray), 30, 255, cv2.THRESH_BINARY)

        # Clean up the difference map
        kernel = np.ones((5,5), np.uint8)
        mask = cv2.morphologyEx(diff, cv2.MORPH_OPEN, kernel)

        # Calculate Anomaly Percentage
        anomaly_score = (np.sum(mask) / (500*500*255)) * 100

        # If the scan is more than 5% different from the healthy one, flag it
        if anomaly_score > 5.0:
            malignant_count += 1
            plt.figure(figsize=(10, 4))
            plt.subplot(1, 2, 1)
            plt.imshow(cv2.cvtColor(orig, cv2.COLOR_BGR2RGB))
            plt.title(f"Scan: {filename}")
            plt.axis('off')

            plt.subplot(1, 2, 2)
            plt.imshow(mask, cmap='hot')
            plt.title(f"⚠️ ANOMALY DETECTED: {anomaly_score:.1f}%")
            plt.axis('off')
            plt.show()

    print(f"\n✅ REPORT: Found {malignant_count} Malignant anomalies out of {len(files)} scans.")

run_anomaly_detection()

"""# Changing anomaly detection percentage"""

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
from google.colab import drive
from tqdm.notebook import tqdm

# --- SECTION 1: SETUP ---
print("🚀 INITIALIZING D3S ANOMALY DETECTION ENGINE...")
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# PATHS
HEALTHY_FOLDER = '/content/drive/MyDrive/Healthy_images_Data'
UNHEALTHY_FOLDER = '/content/drive/MyDrive/Annotated_Data'
OUTPUT_FOLDER = '/content/drive/MyDrive/D3S_Malignant_Results'

if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)

# --- SECTION 2: DYNAMIC NIPPLE MASKING ---

def apply_center_mask(image_cv):
    """
    Suppresses anatomical density at the center of the image
    to avoid False Positives from the nipple.
    """
    h, w = image_cv.shape[:2]
    mask = np.ones((h, w), dtype=np.uint8) * 255
    # Masking a circular region in the dead center
    cv2.circle(mask, (w // 2, h // 2), int(w * 0.18), 0, -1)
    return cv2.bitwise_and(image_cv, image_cv, mask=mask)

# --- SECTION 3: BASELINE MODELING ---

def create_master_healthy_profile(folder_path):
    """
    Averages 4 healthy images to create a noise-free baseline.
    """
    print("🔄 Establishing Statistical Healthy Baseline...")
    images = []
    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.png'))]

    if len(files) == 0:
        raise FileNotFoundError("❌ No images found in Healthy_images_Data folder!")

    for f in files:
        img = cv2.imread(os.path.join(folder_path, f), 0)
        img = cv2.resize(img, (500, 500))
        img = cv2.GaussianBlur(img, (15, 15), 0)
        images.append(img)

    master_profile = np.mean(images, axis=0).astype(np.uint8)
    return master_profile

# --- SECTION 4: DIAGNOSTIC EXECUTION ---

def run_diagnostic_v4_5():
    master_healthy = create_master_healthy_profile(HEALTHY_FOLDER)

    files = [f for f in os.listdir(UNHEALTHY_FOLDER) if f.lower().endswith(('.jpg', '.png'))]
    print(f"🚀 Analyzing {len(files)} proprietary scans against Master Baseline...")

    stats = {'BENIGN': 0, 'MALIGNANT': 0}

    for filename in tqdm(files):
        path = os.path.join(UNHEALTHY_FOLDER, filename)
        img = cv2.imread(path)
        if img is None: continue

        # 1. Processing current scan
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (500, 500))
        gray = cv2.GaussianBlur(gray, (15, 15), 0)

        # 2. Difference Analysis (Anomaly Isolation)
        # We find pixels where current scan is significantly darker than baseline
        diff = cv2.subtract(master_healthy, gray)
        diff = apply_center_mask(diff)

        # 3. Thresholding Significant Density
        _, thresh = cv2.threshold(diff, 45, 255, cv2.THRESH_BINARY)

        # 4. DECISION LOGIC: Changed from 35% to > 15% Anomaly Rule
        anomaly_pixel_count = np.count_nonzero(thresh)
        total_pixels = 500 * 500
        anomaly_percentage = (anomaly_pixel_count / total_pixels) * 100

        # If score >= 15.0%, flag as Malignant
        if anomaly_percentage >= 15.0:
            diagnosis = "MALIGNANT"
            color = 'red'
            # Save flagged image for review
            cv2.imwrite(os.path.join(OUTPUT_FOLDER, f"FLAGGED_{filename}"), img)
        else:
            diagnosis = "BENIGN"
            color = 'green'

        stats[diagnosis] += 1

        # Visualization
        plt.figure(figsize=(12, 4))
        plt.subplot(1, 3, 1)
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title(f"Scan: {filename}")
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(thresh, cmap='hot')
        plt.title(f"Anomaly Map ({anomaly_percentage:.1f}%)")
        plt.axis('off')

        plt.subplot(1, 3, 3)
        plt.text(0.1, 0.5, f"RESULT: {diagnosis}\nScore: {anomaly_percentage:.1f}%\nThreshold: 35.0%",
                 fontsize=12, color=color, fontweight='bold')
        plt.axis('off')
        plt.show()

    # Final Report Summary
    print("\n" + "="*45)
    print("      D3S BASELINE DIAGNOSTIC SUMMARY      ")
    print("="*45)
    for label, count in stats.items():
        pct = (count/len(files))*100
        print(f"{label:<12}: {count:>3} images ({pct:>5.1f}%)")
    print("="*45)
    print(f"📁 Flagged images saved to: {OUTPUT_FOLDER}")

# Run the system
run_diagnostic_v4_5()

"""# Further Refining it to 13 %

"""

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
from google.colab import drive
from tqdm.notebook import tqdm

# --- SECTION 1: SETUP ---
print("🚀 INITIALIZING D3S ANOMALY DETECTION ENGINE (V4.6)...")
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# PATHS
HEALTHY_FOLDER = '/content/drive/MyDrive/Healthy_images_Data'
UNHEALTHY_FOLDER = '/content/drive/MyDrive/Annotated_Data'
OUTPUT_FOLDER = '/content/drive/MyDrive/D3S_Malignant_Results'

if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)

# --- SECTION 2: DYNAMIC NIPPLE MASKING ---

def apply_center_mask(image_cv):
    """Suppresses the nipple region to avoid anatomical False Positives."""
    h, w = image_cv.shape[:2]
    mask = np.ones((h, w), dtype=np.uint8) * 255
    # Masking a circular region in the dead center
    cv2.circle(mask, (w // 2, h // 2), int(w * 0.18), 0, -1)
    return cv2.bitwise_and(image_cv, image_cv, mask=mask)

# --- SECTION 3: BASELINE MODELING ---

def create_master_healthy_profile(folder_path):
    """Averages healthy images to create a noise-free diagnostic baseline."""
    print("🔄 Establishing Statistical Healthy Baseline...")
    images = []
    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.png'))]

    if len(files) == 0:
        raise FileNotFoundError("❌ No images found in Healthy_images_Data folder!")

    for f in files:
        img = cv2.imread(os.path.join(folder_path, f), 0)
        img = cv2.resize(img, (500, 500))
        img = cv2.GaussianBlur(img, (15, 15), 0)
        images.append(img)

    master_profile = np.mean(images, axis=0).astype(np.uint8)
    return master_profile

# --- SECTION 4: DIAGNOSTIC EXECUTION ---

def run_diagnostic_v4_6():
    master_healthy = create_master_healthy_profile(HEALTHY_FOLDER)

    files = [f for f in os.listdir(UNHEALTHY_FOLDER) if f.lower().endswith(('.jpg', '.png'))]
    print(f"🚀 Analyzing {len(files)} proprietary scans against Master Baseline...")

    stats = {'BENIGN': 0, 'MALIGNANT': 0}

    for filename in tqdm(files):
        path = os.path.join(UNHEALTHY_FOLDER, filename)
        img = cv2.imread(path)
        if img is None: continue

        # 1. Processing current scan
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (500, 500))
        gray = cv2.GaussianBlur(gray, (15, 15), 0)

        # 2. Difference Analysis (Anomaly Isolation)
        diff = cv2.subtract(master_healthy, gray)
        diff = apply_center_mask(diff)

        # 3. Thresholding Significant Density
        _, thresh = cv2.threshold(diff, 45, 255, cv2.THRESH_BINARY)

        # 4. DECISION LOGIC: Changed to > 13% Anomaly Rule
        anomaly_pixel_count = np.count_nonzero(thresh)
        total_pixels = 500 * 500
        anomaly_percentage = (anomaly_pixel_count / total_pixels) * 100

        # Threshold update: > 13% is Malignant
        if anomaly_percentage > 13.0:
            diagnosis = "MALIGNANT"
            color = 'red'
            cv2.imwrite(os.path.join(OUTPUT_FOLDER, f"FLAGGED_{filename}"), img)
        else:
            diagnosis = "BENIGN"
            color = 'green'

        stats[diagnosis] += 1

        # Visualization
        plt.figure(figsize=(12, 4))
        plt.subplot(1, 3, 1)
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title(f"Scan: {filename}")
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(thresh, cmap='hot')
        plt.title(f"Anomaly Map ({anomaly_percentage:.1f}%)")
        plt.axis('off')

        plt.subplot(1, 3, 3)
        # Displaying the 15% threshold in the UI
        plt.text(0.1, 0.5, f"RESULT: {diagnosis}\nScore: {anomaly_percentage:.1f}%\nThreshold: 15.0%",
                 fontsize=12, color=color, fontweight='bold')
        plt.axis('off')
        plt.show()

    # Final Report Summary
    print("\n" + "="*45)
    print("      D3S BASELINE DIAGNOSTIC SUMMARY      ")
    print("="*45)
    for label, count in stats.items():
        pct = (count/len(files))*100
        print(f"{label:<12}: {count:>3} images ({pct:>5.1f}%)")
    print("="*45)
    print(f"📁 Flagged images saved to: {OUTPUT_FOLDER}")

# Run the system
run_diagnostic_v4_6()

"""26/2/26"""

!pip install scipy --quiet

import cv2
import numpy as np
import os
import json
import pickle
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
from datetime import datetime
from scipy import stats as scipy_stats
from google.colab import drive

print("✅ All libraries loaded.")

if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')
    print("✅ Google Drive mounted.")
else:
    print("ℹ️  Google Drive already connected.")

CONFIG = {
    # ── Paths ── update these to match your Drive structure
    "healthy_folder":    "/content/drive/MyDrive/Healthy_images_Data",
    "scan_folder":       "/content/drive/MyDrive/Annotated_Data",
    "output_folder":     "/content/drive/MyDrive/D3S_Results_V5",
    "profile_save_path": "/content/drive/MyDrive/D3S_Results_V5/master_healthy_profile.pkl",

    # ── Image processing
    "target_size":       (500, 500),
    "blur_kernel":       (15, 15),
    "diff_threshold":    45,        # pixel intensity cutoff for anomaly map

    # ── Nipple masking (Hough circle detection)
    "nipple_mask_padding":  15,     # extra radius around detected circle
    "hough_dp":             1.2,
    "hough_min_dist":       100,
    "hough_param1":         50,
    "hough_param2":         30,
    "hough_min_radius":     20,
    "hough_max_radius":     65,
    "fallback_mask_radius": 0.18,   # fraction of image width (used if Hough fails)

    # ── Decision logic  ← THE ONLY PLACE TO CHANGE THE THRESHOLD
    "anomaly_threshold_pct": 15.0,  # >= this % → MALIGNANT

    # ── Confidence score weights (must sum to 1.0)
    "conf_weight_margin":    0.50,
    "conf_weight_coherence": 0.30,
    "conf_weight_skew":      0.20,

    # ── Validation split fraction (used in blind test mode)
    "validation_split": 0.15,
}

# Create output folder if it doesn't exist
os.makedirs(CONFIG["output_folder"], exist_ok=True)

print("✅ Configuration set.")
print(f"   Healthy images : {CONFIG['healthy_folder']}")
print(f"   Scan folder    : {CONFIG['scan_folder']}")
print(f"   Output folder  : {CONFIG['output_folder']}")
print(f"   Threshold      : {CONFIG['anomaly_threshold_pct']}%")

def align_to_reference(image: np.ndarray, reference: np.ndarray) -> np.ndarray:
    """
    Aligns a scan to the master profile using ECC (Enhanced Correlation Coefficient).
    Fixes small translation/rotation differences between captures.
    Falls back silently if alignment fails.
    """
    warp_matrix = np.eye(2, 3, dtype=np.float32)
    criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 200, 1e-7)
    try:
        _, warp_matrix = cv2.findTransformECC(
            reference.astype(np.float32),
            image.astype(np.float32),
            warp_matrix,
            cv2.MOTION_EUCLIDEAN,
            criteria
        )
        h, w = reference.shape
        aligned = cv2.warpAffine(
            image, warp_matrix, (w, h),
            flags=cv2.INTER_LINEAR + cv2.WARP_INVERSE_MAP
        )
        return aligned
    except cv2.error:
        return image  # ECC failed — return unaligned rather than crash


def apply_dynamic_nipple_mask(image_gray: np.ndarray) -> tuple:
    """
    V5 FIX: Restored Hough-based nipple detection (replaces V4's fixed center mask).
    The fixed center mask breaks when the nipple is off-center.
    Hough detection finds the actual nipple location regardless of patient positioning.
    Falls back to fixed center mask only if no circle is detected.
    Returns (masked_image, detection_method_used)
    """
    h, w = image_gray.shape[:2]
    blurred = cv2.medianBlur(image_gray, 5)

    circles = cv2.HoughCircles(
        blurred,
        cv2.HOUGH_GRADIENT,
        dp=CONFIG["hough_dp"],
        minDist=CONFIG["hough_min_dist"],
        param1=CONFIG["hough_param1"],
        param2=CONFIG["hough_param2"],
        minRadius=CONFIG["hough_min_radius"],
        maxRadius=CONFIG["hough_max_radius"]
    )

    mask = np.ones((h, w), dtype=np.uint8) * 255

    if circles is not None:
        circles = np.round(circles[0, :]).astype("int")
        x, y, r = circles[0]  # most prominent circle only
        cv2.circle(mask, (x, y), r + CONFIG["nipple_mask_padding"], 0, -1)
        method = "hough"
    else:
        # Fallback only — logged so you can audit which scans used it
        fallback_r = int(w * CONFIG["fallback_mask_radius"])
        cv2.circle(mask, (w // 2, h // 2), fallback_r, 0, -1)
        method = "fallback_center"

    masked = cv2.bitwise_and(image_gray, image_gray, mask=mask)
    return masked, method


def preprocess_scan(image_path: str) -> tuple:
    """
    Loads and preprocesses a single scan.
    Returns (gray_float32, original_bgr) or (None, None) on load failure.
    """
    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        return None, None

    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    gray = cv2.resize(gray, CONFIG["target_size"])
    gray = cv2.GaussianBlur(gray, CONFIG["blur_kernel"], 0)
    return gray, img_bgr


print("✅ Preprocessing functions defined.")

def create_master_healthy_profile() -> np.ndarray:
    """
    Averages all images in healthy_folder into a float32 baseline.

    V5 FIX: Stored as float32, NOT uint8.
    The old .astype(np.uint8) cast quantized the profile and degraded
    every downstream subtraction. float32 preserves full precision.
    """
    folder = CONFIG["healthy_folder"]
    print(f"🔄 Building Master Healthy Profile from: {folder}")

    files = [f for f in os.listdir(folder) if f.lower().endswith(('.jpg', '.png'))]
    if len(files) == 0:
        raise FileNotFoundError(f"❌ No images found in {folder}")

    images = []
    for f in files:
        gray, _ = preprocess_scan(os.path.join(folder, f))
        if gray is not None:
            images.append(gray.astype(np.float32))

    profile = np.mean(images, axis=0)  # float32 throughout
    print(f"✅ Profile built from {len(images)} healthy images.")
    print(f"   Pixel range: [{profile.min():.1f} – {profile.max():.1f}]")

    # Save to Drive for reuse
    save_path = CONFIG["profile_save_path"]
    with open(save_path, 'wb') as f:
        pickle.dump(profile, f)
    print(f"💾 Profile saved to: {save_path}")
    return profile


def load_healthy_profile() -> np.ndarray:
    path = CONFIG["profile_save_path"]
    with open(path, 'rb') as f:
        return pickle.load(f)


# Build or load profile
if os.path.exists(CONFIG["profile_save_path"]):
    print("ℹ️  Existing profile found — loading from Drive.")
    master_profile = load_healthy_profile()
    print(f"✅ Profile loaded. Pixel range: [{master_profile.min():.1f} – {master_profile.max():.1f}]")
else:
    master_profile = create_master_healthy_profile()

def compute_anomaly_map(scan_gray: np.ndarray) -> tuple:
    """
    Core detection logic:
    1. Align scan to master profile (corrects positioning variance)
    2. Directional subtraction: master_healthy - scan
       → Positive values = scan is DARKER than healthy = dense tissue shadow
       → absdiff() is WRONG here — it also flags scan-brighter regions (artifacts)
    3. Apply nipple mask
    4. Threshold + morphological cleaning
    Returns (anomaly_map, mask_method_used)
    """
    scan_f32 = scan_gray.astype(np.float32)
    scan_aligned = align_to_reference(scan_f32, master_profile)

    # Directional subtraction — physics-correct for transillumination
    diff = np.clip(master_profile - scan_aligned, 0, 255).astype(np.uint8)

    # Nipple masking (Hough-based)
    diff_masked, mask_method = apply_dynamic_nipple_mask(diff)

    # Threshold significant density deviations
    _, thresh = cv2.threshold(
        diff_masked, CONFIG["diff_threshold"], 255, cv2.THRESH_BINARY
    )

    # Remove isolated noise pixels
    kernel = np.ones((5, 5), np.uint8)
    anomaly_map = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)

    return anomaly_map, mask_method


def classify_scan(anomaly_map: np.ndarray) -> tuple:
    """
    Returns (diagnosis, anomaly_percentage).
    Threshold comes from CONFIG — not hardcoded here.
    """
    total = anomaly_map.shape[0] * anomaly_map.shape[1]
    count = np.count_nonzero(anomaly_map)
    pct   = (count / total) * 100
    diag  = "MALIGNANT" if pct >= CONFIG["anomaly_threshold_pct"] else "BENIGN"
    return diag, pct


def compute_confidence(anomaly_map: np.ndarray, anomaly_pct: float) -> dict:
    """
    Three-component confidence score [0.0 → 1.0]:

    1. Margin    — how far above/below the threshold is the anomaly score?
    2. Coherence — are anomalous pixels a contiguous mass (real tissue)
                   or scattered noise? High coherence = likely real mass.
    3. Skew      — does the deviation map have a heavy right tail?
                   Dense tissue creates concentrated high-intensity deviations.
    """
    threshold = CONFIG["anomaly_threshold_pct"]

    # 1. Margin (sigmoid centered at threshold)
    margin = float(1 / (1 + np.exp(-0.3 * (anomaly_pct - threshold))))

    # 2. Spatial coherence (largest connected blob / total anomalous pixels)
    binary = (anomaly_map > 0).astype(np.uint8)
    total_anomalous = int(binary.sum())
    if total_anomalous == 0:
        coherence = 0.0
    else:
        n_labels, _, cc_stats, _ = cv2.connectedComponentsWithStats(binary)
        if n_labels < 2:
            coherence = 0.0
        else:
            largest = int(cc_stats[1:, cv2.CC_STAT_AREA].max())
            coherence = float(largest / total_anomalous)

    # 3. Distribution skewness
    skewness   = float(scipy_stats.skew(anomaly_map.flatten().astype(np.float32)))
    skew_score = float(np.clip(skewness / 3.0, 0.0, 1.0))

    composite = (
        CONFIG["conf_weight_margin"]    * margin    +
        CONFIG["conf_weight_coherence"] * coherence +
        CONFIG["conf_weight_skew"]      * skew_score
    )

    grade = (
        "HIGH"     if composite >= 0.85 else
        "MODERATE" if composite >= 0.60 else
        "LOW"      if composite >= 0.40 else
        "BENIGN"
    )

    return {
        "composite": round(composite, 3),
        "margin":    round(margin, 3),
        "coherence": round(coherence, 3),
        "skew":      round(skew_score, 3),
        "grade":     grade
    }


print("✅ Detection and scoring functions defined.")

def visualize_result(original_bgr, anomaly_map, filename,
                     diagnosis, anomaly_pct, confidence, save_path=None):
    """
    Four-panel output:
    [Original Scan] [Anomaly Map] [Overlay] [Diagnosis Report]
    """
    original_rgb = cv2.cvtColor(
        cv2.resize(original_bgr, CONFIG["target_size"]),
        cv2.COLOR_BGR2RGB
    )

    heatmap_color = cv2.applyColorMap(anomaly_map, cv2.COLORMAP_HOT)
    heatmap_rgb   = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    overlay       = cv2.addWeighted(original_rgb, 0.6, heatmap_rgb, 0.4, 0)

    fig, axes = plt.subplots(1, 4, figsize=(20, 5))
    fig.patch.set_facecolor('#0d0d0d')
    title_color = '#ff4444' if diagnosis == 'MALIGNANT' else '#44ff88'
    fig.suptitle(f"D3S BR-Scan  ·  {filename}", fontsize=12,
                 fontweight='bold', color='white')

    for ax in axes:
        ax.set_facecolor('#1a1a1a')

    axes[0].imshow(original_rgb)
    axes[0].set_title("Original Scan", color='white', fontsize=10)
    axes[0].axis('off')

    axes[1].imshow(anomaly_map, cmap='hot')
    axes[1].set_title(f"Anomaly Map  ({anomaly_pct:.1f}%)", color='white', fontsize=10)
    axes[1].axis('off')

    axes[2].imshow(overlay)
    axes[2].set_title("Overlay", color='white', fontsize=10)
    axes[2].axis('off')

    # Diagnosis panel
    verdict_symbol = "⚠️  MALIGNANT" if diagnosis == "MALIGNANT" else "✅  BENIGN"
    report = (
        f"{verdict_symbol}\n\n"
        f"Anomaly Score : {anomaly_pct:.1f}%\n"
        f"Threshold     : {CONFIG['anomaly_threshold_pct']:.1f}%\n\n"
        f"━━━━━━━━━━━━━━━━━━\n"
        f"Confidence    : {confidence['composite']*100:.1f}%\n"
        f"Grade         : {confidence['grade']}\n\n"
        f"  Margin      : {confidence['margin']*100:.0f}%\n"
        f"  Coherence   : {confidence['coherence']*100:.0f}%\n"
        f"  Skew        : {confidence['skew']*100:.0f}%"
    )
    axes[3].text(0.08, 0.92, report,
                 transform=axes[3].transAxes,
                 fontsize=9.5, color=title_color,
                 fontweight='bold', verticalalignment='top',
                 fontfamily='monospace')
    axes[3].set_title("Diagnosis", color='white', fontsize=10)
    axes[3].axis('off')

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=100, bbox_inches='tight',
                    facecolor=fig.get_facecolor())
    plt.show()
    plt.close()


print("✅ Visualization function defined.")

VALIDATION_MODE = False   # ← change to True for blind validation pass

# ── collect files ──────────────────────────────────────────────
scan_folder   = CONFIG["scan_folder"]
output_folder = CONFIG["output_folder"]
files = sorted([f for f in os.listdir(scan_folder)
                if f.lower().endswith(('.jpg', '.png'))])

if VALIDATION_MODE:
    np.random.seed(42)
    indices = np.random.permutation(len(files))
    n_val   = max(1, int(len(files) * CONFIG["validation_split"]))
    files   = [files[i] for i in indices[:n_val]]
    print(f"🔬 VALIDATION MODE: {n_val} held-out scans.")
else:
    print(f"🚀 FULL BATCH MODE: {len(files)} scans.")

# ── main loop ──────────────────────────────────────────────────
stats   = {"MALIGNANT": 0, "BENIGN": 0}
results = []
fallback_count = 0

for filename in tqdm(files, desc="Analyzing BR-Scans"):
    path = os.path.join(scan_folder, filename)
    scan_gray, original_bgr = preprocess_scan(path)

    if scan_gray is None:
        print(f"  ⚠️  Could not load {filename} — skipping.")
        continue

    anomaly_map, mask_method   = compute_anomaly_map(scan_gray)
    diagnosis, anomaly_pct     = classify_scan(anomaly_map)
    confidence                 = compute_confidence(anomaly_map, anomaly_pct)

    if mask_method == "fallback_center":
        fallback_count += 1

    stats[diagnosis] += 1
    results.append({
        "scan_id":     filename,
        "diagnosis":   diagnosis,
        "anomaly_pct": round(anomaly_pct, 2),
        "confidence":  confidence,
        "mask_method": mask_method,
        "timestamp":   datetime.now().isoformat()
    })

    # Save flagged scan image
    if diagnosis == "MALIGNANT":
        cv2.imwrite(os.path.join(output_folder, f"FLAGGED_{filename}"), original_bgr)

    # Save visualization
    viz_path = os.path.join(output_folder, f"ANALYSIS_{filename.rsplit('.', 1)[0]}.png")
    visualize_result(original_bgr, anomaly_map, filename,
                     diagnosis, anomaly_pct, confidence,
                     save_path=viz_path)

# ── summary ────────────────────────────────────────────────────
total = sum(stats.values())
print("\n" + "="*52)
print("         D3S BR-SCAN DIAGNOSTIC SUMMARY V5        ")
print("="*52)
for label, count in stats.items():
    pct = (count / total * 100) if total > 0 else 0
    bar = "█" * int(pct / 2)
    print(f"  {label:<12}: {count:>4}  ({pct:>5.1f}%)  {bar}")
print(f"\n  Decision threshold : {CONFIG['anomaly_threshold_pct']}%")
print(f"  Total analyzed     : {total}")
print(f"  Hough fallbacks    : {fallback_count}  ← review these scans")
print("="*52)

# ── save JSON audit trail ──────────────────────────────────────
report_path = os.path.join(output_folder, "diagnostic_report.json")
with open(report_path, 'w') as f:
    json.dump({
        "config":    CONFIG,
        "summary":   stats,
        "results":   results,
        "generated": datetime.now().isoformat()
    }, f, indent=2)
print(f"\n💾 Full audit trail saved to: {report_path}")
print(f"📁 Flagged images saved to  : {output_folder}")

scores      = [r["anomaly_pct"] for r in results]
confidences = [r["confidence"]["composite"] * 100 for r in results]
diagnoses   = [r["diagnosis"] for r in results]
colors      = ['#ff4444' if d == 'MALIGNANT' else '#44ff88' for d in diagnoses]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.patch.set_facecolor('#0d0d0d')
fig.suptitle("D3S BR-Scan — Batch Results Dashboard", color='white',
             fontsize=13, fontweight='bold')

for ax in axes:
    ax.set_facecolor('#1a1a1a')
    ax.tick_params(colors='white')
    ax.xaxis.label.set_color('white')
    ax.yaxis.label.set_color('white')
    ax.title.set_color('white')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444')

# Panel 1: Anomaly score distribution
axes[0].hist(scores, bins=20, color='#ff6b35', edgecolor='#0d0d0d', alpha=0.85)
axes[0].axvline(CONFIG["anomaly_threshold_pct"], color='white',
                linestyle='--', linewidth=1.5, label=f"Threshold {CONFIG['anomaly_threshold_pct']}%")
axes[0].set_title("Anomaly Score Distribution")
axes[0].set_xlabel("Anomaly %")
axes[0].set_ylabel("Count")
axes[0].legend(labelcolor='white', facecolor='#1a1a1a', edgecolor='#444')

# Panel 2: Confidence vs Anomaly Score scatter
axes[1].scatter(scores, confidences, c=colors, alpha=0.75, s=40, edgecolors='none')
axes[1].axvline(CONFIG["anomaly_threshold_pct"], color='white',
                linestyle='--', linewidth=1.5)
axes[1].set_title("Confidence vs Anomaly Score")
axes[1].set_xlabel("Anomaly %")
axes[1].set_ylabel("Confidence %")
from matplotlib.lines import Line2D
legend_elements = [
    Line2D([0], [0], marker='o', color='w', markerfacecolor='#ff4444',
           markersize=8, label='Malignant'),
    Line2D([0], [0], marker='o', color='w', markerfacecolor='#44ff88',
           markersize=8, label='Benign'),
]
axes[1].legend(handles=legend_elements, labelcolor='white',
               facecolor='#1a1a1a', edgecolor='#444')

# Panel 3: Pie chart
mal_count = stats.get("MALIGNANT", 0)
ben_count = stats.get("BENIGN", 0)
wedge_colors = ['#ff4444', '#44ff88']
wedges, texts, autotexts = axes[2].pie(
    [mal_count, ben_count],
    labels=["Malignant", "Benign"],
    colors=wedge_colors,
    autopct='%1.1f%%',
    startangle=140,
    textprops={'color': 'white', 'fontsize': 11}
)
for at in autotexts:
    at.set_color('white')
    at.set_fontweight('bold')
axes[2].set_title("Diagnosis Split")

plt.tight_layout()
plt.savefig(os.path.join(output_folder, "dashboard.png"),
            dpi=120, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()
print("📊 Dashboard saved.")